### ISSUE TITLE
Digdir´s Strategic Alignment and Stakeholder Engagement in Lean Portfolio Management

### ISSUE THREAD

**Issue by MrCarrera** [digdir/baksia#611]
### Description

As Digdir employee working in product development such as Altinn and Fellesdatakatalog, I wan to know how the Lean Portfolio operates. For transparency purposes, alignment when we prioritise our work both with my team and how we collaborate with other teams. I want to get answers about: How  the initiatives we work on, align with the department and digdir goals? What are the roles and functions the the lean portfolio? What specific data an initiative needs to build upon to move from one phase to another in the portfolio? What forums, ceremonies the portfolio review the diferent initiatives and how they address the challenges. 

### In scope

Portfolio for Altinn and Felles Data Katalog at Digdir/Brukeropplevelse og Datadeling department

### Out of scope

Portfolio for the entirely Digdir. 

### Additional Information

Lean Portfolio Management
https://www.atlassian.com/agile/agile-at-scale/lean-portfolio-management

### Tasks

- [x] As a Lean Porfolio Manager, I need a clear mapping and flow of each initiative to our strategic goals, so I can prioritize projects that offer the highest alignment and potential impact.
- [x] As an assignee to move forward an initiative to the portfolio flow, I need documented criteria for each phase, so I can ensure architectural decisions, funding, design and strategic alignment to support the transition from concept through to completion. 
- [x] As a product owner, I need a clear view of whereas my team is involved in collaboration efforts to acheive the outcomes of the initiative.

**Comment by fsveinsb** [comment]
@MrCarrera 
1) Dette punktet svarer delvis utført på.
"As a Lean Porfolio Manager, I need a clear mapping and flow of each initiative to our strategic goals, so I can prioritize projects that offer the highest alignment and potential impact"

Strategier er løpende under utarbeidelse. Vi bruker MoSCoW ved prioritering av tiltak. I den grad strategier for produkt og produktgrupper foreligger legges disse også til grunn ved prioritering.  

2) Dette punktet er ivaretatt:
"As an assignee to move forward an initiative to the portfolio flow, I need documented criteria for each phase, so I can ensure architectural decisions, funding, design and strategic alignment to support the transition from concept through to completion"

Beskrivelse av faseoverganger ligger her: https://github.com/digdir/portfolio

3) Dette punktet er ivaretatt:
"As a product owner, I need a clear view of whereas my team is involved in collaboration efforts to acheive the outcomes of the initiative."

I malen for de enkelte porteføljetiltak skal steakholder listes. Disse skal følges opp som del av gjennomføring av tiltaket

**Comment by MrCarrera** [comment]
@fsveinsb Moved back to "revise status" as Sigurd needs to move this further in Baksia according to the design he wants to implement. for the content you have provided.  If the content is not clear, then @sorensensig will need to contact you for clarifications.

**Comment by MrCarrera** [comment]
@Removing Frank Robert as assigned, and replace to Sigurd to follow up-
