### ISSUE TITLE
Update illustrations of POM and Team Typologies to v2

### ISSUE THREAD

**Issue by sorensensig** [digdir/baksia#652]
Update #636 with a new version (v2).

```[tasklist]
### Tasks - Mobile friendly version
- [x] export desktop versions as svg
- [ ] export mobile versions as svg
```

```[tasklist]
### Tasks - Mobile friendly version
- [ ] pom-flow-map
- [ ] pom-vs-sections
- [ ] team-overview
```

**Comment by sorensensig** [comment]
## Desktop versions in svg file format
[svg.zip](https://github.com/user-attachments/files/15986143/svg.zip)

**Comment by altinnadmin** [comment]
@sorensensig Desktop-versions (svg) currently looks like this on mobile. And of course, no problem zooming. https://baksia.digdir.no/produktutviklingsmodell/

![Image](https://github.com/digdir/baksia/assets/6088624/057b6668-760c-4237-a015-7b4fea8ae696)

**Comment by sorensensig** [comment]
Great! This is sufficient for now. I'd rather go back and finetune the illustrations once we start looking at the future state of POM.

Closing this issue as done.
